steps:
  - name : 'gcr.io/cloud-builders/docker'
    args: ["build", "--platform", "linux/amd64", "-t", 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',"."]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - '$REPO_NAME'
    - '--image'
    - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
    - '--region'
    - 'asia-southeast2'
  # - name: 'gcr.io/cloud-builders/gke'
  #   args: [ 'deploy', '$REPO_NAME', '--image', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '--port', '80' ]
images: ['gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '--allow-unauthenticated']
  # timeout: "1600s"
