version: "3"
services:
  app:
    build:
      args:
        user: creasi
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: creasi
    container_name: creasi-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - creasi
    command: sh -c "php artisan migrate --seed --force && php artisan serve --host=0.0.0.0 --port=8080"

  mysql:
    container_name: creasi-mysql
    image: marketplace.gcr.io/google/mysql8
    environment:
      MYSQL_ONETIME_PASSWORD: "yes"
    #   "MYSQL_RANDOM_ROOT_PASSWORD": "yes"
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - '3306:3306'
    networks:
      - creasi

#   db:
#     image: mysql:8.0
#     container_name: creasi-db
#     restart: unless-stopped
#     environment:
#       MYSQL_DATABASE: ${DB_DATABASE}
#       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#       MYSQL_PASSWORD: ${DB_PASSWORD}
#       MYSQL_USER: ${DB_USERNAME}
#       SERVICE_TAGS: dev
#       SERVICE_NAME: mysql
#     volumes:
#       - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    # networks:
    #   - creasi

  nginx:
    image: nginx:alpine
    container_name: creasi-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/app
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - creasi

networks:
  creasi:
    driver: bridge
