version: '3'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: creasi
      MYSQL_USER: creasi
      MYSQL_PASSWORD: password
  php:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
